[MeterImage]
Meter=Image
ImageName=#@#Images\Scrap\time.png
SolidColor=0,0,0,1

[MeterTime]
Meter=String
MeterStyle=FontFormat_Large
MeasureName=MeasureTime_Clock
StringAlign=Center
X=84
Y=11

[MeterHourHand]
Meter=Roundline
MeasureName=MeasureTime
X=23
Y=28
LineLength=6
LineColor=235,245,229,255
LineWidth=2
StartAngle=4.7124
RotationAngle=6.2832
ValueRemainder=43200
AntiAlias=1

[MeterMinuteHand]
Meter=Roundline
MeasureName=MeasureTime
X=23
Y=28
LineLength=8
LineColor=235,245,229,255
LineWidth=2
StartAngle=4.7124
RotationAngle=6.2832
ValueRemainder=3600
AntiAlias=1
