[FontFormat_Large]
FontSize=16
FontFace=SuperText 02 Bold
FontColor=235,245,229,255

[FontFormat_Medium]
FontSize=24
FontFace=ccnew

FontColor=235,245,229,255

[FontFormat_Small]
FontSize=12
FontFace=JustinFont8
FontColor=235,245,229,255

[FontFormat_Label]
FontSize=10
FontFace=C&C Red Alert [INET]
FontColor=243,255,230,255

[MeterFormat_Histogram]
W=79
H=33
PrimaryColor=243,255,230,255

[MeterFormat_DriveLabel]
FontSize=12
FontFace=JustinFont8
FontColor=235,245,229,255
ClipString=1
StringAlign=CenterTop
H=20

[MeterFormat_DriveSize]
FontSize=12
FontFace=JustinFont8
FontColor=235,245,229,255
ClipString=1
StringAlign=LeftTop
NumOfDecimals=0
Autoscale=1
H=20
W=81

